# Generated by Django 4.2.5 on 2023-09-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Resim')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', models.CharField(max_length=2000, verbose_name='İçerik')),
                ('history', models.CharField(max_length=2000, verbose_name='Tarihçe')),
                ('city', models.CharField(choices=[('ADANA', 'Adana'), ('ADIYAMAN', 'Adıyaman'), ('AFYONKARAHISAR', 'Afyonkarahisar'), ('AGRI', 'Ağrı'), ('AMASYA', 'Amasya'), ('ANKARA', 'Ankara'), ('ANTALYA', 'Antalya'), ('ARTVIN', 'Artvin'), ('AYDIN', 'Aydın'), ('BALIKESIR', 'Balikesir'), ('BILECIK', 'Bilecik'), ('BINGOL', 'Bingol'), ('BITLIS', 'Bitlis'), ('BOLU', 'Bolu'), ('BURDUR', 'Burdur'), ('BURSA', 'Bursa'), ('CANAKKALE', 'Çanakkale'), ('CANKIRI', 'Çankiri'), ('CORUM', 'Çorum'), ('DENIZLI', 'Denizli'), ('DIYARBAKIR', 'Diyarbakır'), ('EDIRNE', 'Edirne'), ('ELAZIG', 'Elazığ'), ('ERZINCAN', 'Erzincan'), ('ERZURUM', 'Erzurum'), ('ESKISEHIR', 'Eskişehir'), ('GAZIANTEP', 'Gaziantep'), ('GIRESUN', 'Giresun'), ('GUMUSHANE', 'Gumuşhane'), ('HAKKARI', 'Hakkari'), ('HATAY', 'Hatay'), ('ISPARTA', 'Isparta'), ('MERSIN', 'Mersin'), ('ISTANBUL', 'İstanbul'), ('IZMIR', 'İzmir'), ('KARS', 'Kars'), ('KASTAMONU', 'Kastamonu'), ('KAYSERI', 'Kayseri'), ('KIRKLARELI', 'Kırklareli'), ('KIRSEHIR', 'Kırşehir'), ('KOCAELI', 'Kocaeli'), ('KONYA', 'Konya'), ('KUTAHYA', 'Kütahya'), ('MALATYA', 'Malatya'), ('MANISA', 'Manisa'), ('KAHRAMANMARAŞ', 'Kahramanmaraş'), ('MARDIN', 'Mardin'), ('MUGLA', 'Muğla'), ('MUS', 'Muş'), ('NEVSEHIR', 'Nevşehir'), ('NIGDE', 'Niğde'), ('ORDU', 'Ordu'), ('RIZE', 'Rize'), ('SAKARYA', 'Sakarya'), ('SAMSUN', 'Samsun'), ('SIIRT', 'Siirt'), ('SINOP', 'Sinop'), ('SIVAS', 'Sivas'), ('TEKIRDAĞ', 'Tekirdağ'), ('TOKAT', 'Tokat'), ('TRABZON', 'Trabzon'), ('TUNCELI', 'Tunceli'), ('SANLIURFA', 'Şanlıurfa'), ('USAK', 'Uşak'), ('VAN', 'Van'), ('YOZGAT', 'Yozgat'), ('ZONGULDAK', 'Zonguldak'), ('AKSARAY', 'Aksaray'), ('BAYBURT', 'Bayburt'), ('KARAMAN', 'Karaman'), ('KIRIKKALE', 'Kırıkkale'), ('BATMAN', 'Batman'), ('SIRNAK', 'Şırnak'), ('BARTIN', 'Bartın'), ('ARDAHAN', 'Ardahan'), ('IGDIR', 'Iğdır'), ('KARABUK', 'Karabük'), ('KILIS', 'Kilis'), ('OSMANIYE', 'Osmaniye'), ('DUZCE', 'Düzce')], max_length=20, verbose_name='İl')),
                ('is_activate', models.BooleanField(verbose_name='Aktif')),
            ],
        ),
    ]
