from django.db import models

# Create your models here.
class Post(models.Model):
    class City(models.TextChoices):
        ADANA = "ADANA", "Adana"
        ADIYAMAN = "ADIYAMAN", "Adıyaman"
        AFYONKARAHISAR = "AFYONKARAHISAR", "Afyonkarahisar"
        AGRI = "AGRI", "Ağrı"
        AMASYA = "AMASYA", "Amasya"
        ANKARA = "ANKARA", "Ankara"
        ANTALYA = "ANTALYA", "Antalya"
        ARTVIN = "ARTVIN", "Artvin"
        AYDIN = "AYDIN", "Aydın"
        BALIKESIR = "BALIKESIR", "Balikesir"
        BILECIK = "BILECIK", "Bilecik"
        BINGOL = "BINGOL", "Bingol"
        BITLIS = "BITLIS", "Bitlis"
        BOLU = "BOLU", "Bolu"
        BURDUR = "BURDUR", "Burdur"
        BURSA = "BURSA", "Bursa"
        CANAKKALE = "CANAKKALE", "Çanakkale"
        CANKIRI = "CANKIRI", "Çankiri"
        CORUM = "CORUM", "Çorum"
        DENIZLI = "DENIZLI", "Denizli"
        DIYARBAKIR = "DIYARBAKIR", "Diyarbakır"
        EDIRNE = "EDIRNE", "Edirne"
        ELAZIG = "ELAZIG", "Elazığ"
        ERZINCAN = "ERZINCAN", "Erzincan"
        ERZURUM = "ERZURUM", "Erzurum"
        ESKISEHIR = "ESKISEHIR", "Eskişehir"
        GAZIANTEP = "GAZIANTEP", "Gaziantep"
        GIRESUN = "GIRESUN", "Giresun"
        GUMUSHANE = "GUMUSHANE", "Gumuşhane"
        HAKKARI = "HAKKARI", "Hakkari"
        HATAY = "HATAY", "Hatay"
        ISPARTA = "ISPARTA", "Isparta"
        MERSIN = "MERSIN", "Mersin"
        ISTANBUL = "ISTANBUL", "İstanbul"
        IZMIR = "IZMIR", "İzmir"
        KARS = "KARS", "Kars"
        KASTAMONU = "KASTAMONU", "Kastamonu"
        KAYSERI = "KAYSERI", "Kayseri"
        KIRKLARELI = "KIRKLARELI", "Kırklareli"
        KIRSEHIR = "KIRSEHIR", "Kırşehir"
        KOCAELI = "KOCAELI", "Kocaeli"
        KONYA = "KONYA", "Konya"
        KUTAHYA = "KUTAHYA", "Kütahya"
        MALATYA = "MALATYA", "Malatya"
        MANISA = "MANISA", "Manisa"
        KAHRAMANMARAS = "KAHRAMANMARAŞ", "Kahramanmaraş"
        MARDIN = "MARDIN", "Mardin"
        MUGLA = "MUGLA", "Muğla"
        MUS = "MUS", "Muş"
        NEVSEHIR = "NEVSEHIR", "Nevşehir"
        NIGDE = "NIGDE", "Niğde"
        ORDU = "ORDU", "Ordu"
        RIZE = "RIZE", "Rize"
        SAKARYA = "SAKARYA", "Sakarya"
        SAMSUN = "SAMSUN", "Samsun"
        SIIRT = "SIIRT", "Siirt"
        SINOP = "SINOP", "Sinop"
        SIVAS = "SIVAS", "Sivas"
        TEKIRDAĞ = "TEKIRDAĞ", "Tekirdağ"
        TOKAT = "TOKAT", "Tokat"
        TRABZON = "TRABZON", "Trabzon"
        TUNCELI = "TUNCELI", "Tunceli"
        SANLIURFA = "SANLIURFA", "Şanlıurfa"
        USAK = "USAK", "Uşak"
        VAN = "VAN", "Van"
        YOZGAT = "YOZGAT", "Yozgat"
        ZONGULDAK = "ZONGULDAK", "Zonguldak"
        AKSARAY = "AKSARAY", "Aksaray"
        BAYBURT = "BAYBURT", "Bayburt"
        KARAMAN = "KARAMAN", "Karaman"
        KIRIKKALE = "KIRIKKALE", "Kırıkkale"
        BATMAN = "BATMAN", "Batman"
        SIRNAK = "SIRNAK", "Şırnak"
        BARTIN = "BARTIN", "Bartın"
        ARDAHAN = "ARDAHAN", "Ardahan"
        IGDIR = "IGDIR", "Iğdır"
        KARABUK = "KARABUK", "Karabük"
        KILIS = "KILIS", "Kilis"
        OSMANIYE = "OSMANIYE", "Osmaniye"
        DUZCE = "DUZCE", "Düzce"

    image = models.ImageField(verbose_name="Resim")
    title = models.CharField(max_length=100, null=False, verbose_name="Başlık")
    content = models.CharField(max_length=2000, null=False, verbose_name="İçerik")
    history = models.CharField(max_length=2000, null=False, verbose_name="Tarihçe")
    city = models.CharField(max_length=20, verbose_name="İl", choices=City.choices)
    is_activate = models.BooleanField(verbose_name="Aktif")

